/* generated by pull.js */
import _js from "./userscript.js";
import _css from "./userstyle.css?raw";
import _css2 from "./hide-labels.css?raw";
import _css3 from "./sprite-properties.css?raw";
import _asset from "./close.svg";
export const resources = {
  "userscript.js": _js,
  "userstyle.css": _css,
  "hide-labels.css": _css2,
  "sprite-properties.css": _css3,
  "close.svg": _asset,
};
