/* generated by pull.js */
const manifest = {
    "name": "Remove Logo",
    "description": "Removes the logo so it doesn't take as much space.",
    "credits": [
        {
            "name": "MrIncredibleMaker",
            "link": "https://scratch.mit.edu/users/MrIncredibleMakerZe/"
        }
    ],
    "userscripts": [
        {
            "url": "userscript.js"
        }
    ],
    "tags": ["new"],
    "enabledByDefault": false,
};
export default manifest;