/* generated by pull.js */
const manifest = {
    "name": "Custom website font (Scratch Tools)",
    "description": "Changes the font of the site. The Input is case-sensitive with Google-Fonts.",
    "credits": [
      {
        "name": "Scratchfangs",
        "link": "https://scratch.mit.edu/users/Scratchfangs/"
      },
      {
        "name": "devxan",
        "link": "https://github.com/devxan"
      },
      {
        "name": "rgantzos",
        "link": "https://scratch.mit.edu/users/rgantzos/"
      },
      {
        "name": "MrIncredibleMakerZe",
        "link": "https://scratch.mit.edu/users/MrIncredibleMakerZe/"
      }
    ],
    "tags": [
      "theme",
      "new"
    ],
    "enabledByDefault": false,
    "settings": [
      {
        "dynamic": true,
        "id": "fontsource",
        "name": "Select Font Source",
        "type": "select",
        "potentialValues": [
          {
            "id": "penguinmod",
            "name": "Penguinmod"
          },
          {
            "id": "google",
            "name": "Google Fonts"
          }
        ],
        "default": "google"
      },
      {
        "dynamic": true,
        "name": "Font Name",
        "id": "webFont",
        "type": "text",
        "default": ""
      }
    ],
    "userstyles": [],
    "userscripts": [
      {
        "url": "userscript.js"
      }
    ],
    "dynamicDisable": true
  };
  export default manifest;