/* generated by pull.js */
const manifest = {
    "name": "Multi Sprite Selecting",
    "description": "Doesn't work right now.",
    "editorOnly": true,
    "noTranslations": true,
    "credits": [
        {
            "name": "MrIncredibleMaker",
            "link": "https://scratch.mit.edu/users/MrIncredibleMakerZe/"
        }
    ],
    "userscripts": [
        {
            "url": "userscript.js"
        }
    ],
    "userstyles": [
        {
          "url": "multi-sprite-selecting.css"
        }
    ],
    "tags": ["beta", "new"],
    "enabledByDefault": false,
};
export default manifest;