/* generated by pull.js */
const manifest = {
    "editorOnly": true,
    "noTranslations": true,
    "name": "Paint Editor Collapse buttons",
    "description": "Collapse parts of the paint editor with buttons.",
    "credits": [
        {
            "name": "MrIncredibleMaker",
            "link": "https://scratch.mit.edu/users/MrIncredibleMakerZe/"
        }
    ],
    "info": [
        {
            "text": "This is still a work in progress so there are probably lots of bugs.",
            "id": "wip"
        }
    ],
    "userscripts": [
        {
            "url": "userscript.js"
        }
    ],
    "dynamicEnable": true,
    "dynamicDisable": false,
    "tags": ["new", "beta", "dinosaurmod"],
    "enabledByDefault": true
};
export default manifest;
