/* generated by pull.js */
const manifest = {
    "editorOnly": true,
    "noTranslations": true,
    "name": "Paint editor collapse buttons",
    "description": "Collapse parts of the paint editor with buttons.",
    "credits": [
        {
            "name": "MrIncredibleMaker",
            "link": "https://scratch.mit.edu/users/MrIncredibleMakerZe/"
        }
    ],
    /*"info": [
        {
            "text": "This addon is still a work in progress so there are lots of bugs.",
            "id": "wip"
        }
    ],*/
    "userscripts": [
        {
            "url": "userscript.js"
        }
    ],
    "dynamicEnable": true,
    "dynamicDisable": false,
    "tags": ["new", "beta", "dinosaurmod"],
    "enabledByDefault": false
};
export default manifest;
