/* generated by pull.js */
const manifest = {
  "enabledByDefault": true,
  "editorOnly": true,
  "name": "Move sprites to first or last",
  "description": "Adds options to the right click context menu for sprites to move them to the very first or the very last of the list.",
  "info": [
    {
      "text": "This addon is inspired by the \"Move costume to top or bottom\" addon.",
      "id": "inspiration"
    }
  ],
  "tags": ["dinosaurmod", "new"],
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "dynamicDisable": true
};
export default manifest;
